Update behavior_ophys_dataset.py
Fixes outdated nwb directory pathing causing the following bug:

Traceback (most recent call last):
  File "/root/capsule/code/extract_lamf_session_data.py", line 128, in <module>
    bmod = BehaviorMultiplaneOphysDataset(session_folder_path=Path(processed_path), 
  File "/comb/src/comb/behavior_ophys_dataset.py", line 141, in __init__
    self._get_ophys_datasets()
  File "/comb/src/comb/behavior_ophys_dataset.py", line 151, in _get_ophys_datasets
    self.ophys_datasets[opid] = OphysPlaneDataset(plane_folder, 
  File "/comb/src/comb/ophys_plane_dataset.py", line 64, in __init__
    self.metadata = self._set_metadata()
  File "/comb/src/comb/ophys_plane_dataset.py", line 215, in _set_metadata
    split_dict = self._parse_mesoscope_metadata()
  File "/comb/src/comb/ophys_plane_dataset.py", line 191, in _parse_mesoscope_metadata
    assert len(matched_inds) == 1, "Could not find a unique match for plane in session.json"
AssertionError: Could not find a unique match for plane in session.json